version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exness
    volumes:
      - ./packages/database/sql:/docker-entrypoint-initdb.d

  zookeeper: 
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"

  kafka: 
    image: wurstmeister/kafka
    container_name: kafka-exness
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  admin:
    image: postgres:15
    container_name: admin
    depends_on:
      - postgres
    volumes:
      - ./packages/database/sql:/sql
      - ./scripts:/scripts
    environment:
      RESET_MODE: drop   # can be drop | truncate | create
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exness
    entrypoint: ["/bin/bash", "/scripts/reset_ticks.sh"]
